version: "3.9"

services:
  backend:
    build: ./backend
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT:-8000} --reload
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      - postgres
      - redis

  celery-worker:
    build: ./backend
    env_file: .env
    command: celery -A app.tasks.celery_app.celery_app worker --loglevel=INFO
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
      - postgres

  frontend:
    build: ./frontend
    env_file: .env
    command: npm run dev -- --host 0.0.0.0 --port ${FRONTEND_PORT:-5173}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ranobe}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"

volumes:
  postgres_data:
