# ПРИМЕЧАНИЕ: Для бесплатного деплоймента используем Upstash.com для Redis!
# 
# Этот Blueprint НЕ создает Redis. Создайте Redis на Upstash.com:
#
# 1. Backend (Web Service):
#    - New → Web Service → Python
#    - Plan: Free
#    - Build Command: cd backend && pip install -r requirements.txt && python init_db.py
#    - Start Command: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
#    - Health Check Path: /health
#
# 2. Frontend (Static Site):
#    - New → Static Site
#    - Plan: Free
#    - Build Command: cd frontend && npm install && npm run build
#    - Publish Directory: frontend/dist
#
# 3. Redis (Upstash.com):
#    - Создайте на upstash.com
#    - Получите connection string
#    - Добавьте в переменные окружения backend
#
# 4. Настройте переменные окружения в каждом сервисе
# 5. Используйте Neon.tech для PostgreSQL
#
# Преимущества Upstash Redis:
# - 256MB data size (больше чем Render)
# - 500K commands per month
# - Более стабильный сервис
# - Лучшая производительность
