services:
  # Redis сервис (единственный в Blueprint)
  - type: redis
    name: lightnovel-redis
    plan: free
    ipAllowList: [] # только внутренние соединения

# ПРИМЕЧАНИЕ: Для бесплатного деплоймента рекомендуется ручное создание!
# 
# Этот Blueprint создает только Redis. Остальные сервисы создайте вручную:
#
# 1. Backend (Web Service):
#    - New → Web Service → Python
#    - Plan: Free
#    - Build Command: cd backend && pip install -r requirements.txt && python init_db.py
#    - Start Command: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
#    - Health Check Path: /health
#
# 2. Frontend (Static Site):
#    - New → Static Site
#    - Plan: Free
#    - Build Command: cd frontend && npm install && npm run build
#    - Publish Directory: frontend/dist
#
# 3. Настройте переменные окружения в каждом сервисе
# 4. Используйте Neon.tech для PostgreSQL
#
# Преимущества ручного создания:
# - Полный контроль над каждым сервисом
# - Бесплатные планы доступны для всех сервисов
# - Простота и гибкость настройки
