services:
  # Redis сервис (бесплатный)
  - type: redis
    name: lightnovel-redis
    plan: free
    ipAllowList: [] # только внутренние соединения

# ПРИМЕЧАНИЕ: Background Worker не поддерживает бесплатный план в Render
# 
# Для бесплатного деплоймента:
# 1. Запустите этот Blueprint для Redis (бесплатно)
# 2. Создайте web services (backend и frontend) вручную в Render Dashboard с plan: free
# 3. Создайте background worker вручную в Render Dashboard (платно) или используйте альтернативы
# 4. Используйте Neon.tech для PostgreSQL базы данных
# 5. Настройте переменные окружения вручную
#
# Альтернативы для background worker:
# - Используйте платный worker в Render
# - Используйте внешние сервисы (Upstash QStash, Cloudflare Workers)
# - Запускайте Celery локально для разработки
