# ПРИМЕЧАНИЕ: Docker деплоймент для упрощения процесса!
# 
# Этот Blueprint НЕ создает Redis. Создайте Redis на Upstash.com:
#
# 1. Backend (Web Service):
#    - New → Web Service → Docker
#    - Plan: Free
#    - Docker Image: будет собран автоматически из Dockerfile
#    - Health Check Path: /health
#
# 2. Frontend (Static Site):
#    - New → Static Site
#    - Plan: Free
#    - Build Command: cd frontend && npm install && npm run build
#    - Publish Directory: frontend/dist
#
# 3. Redis (Upstash.com):
#    - Создайте на upstash.com
#    - Получите connection string
#    - Добавьте в переменные окружения backend
#
# 4. Настройте переменные окружения в каждом сервисе
# 5. Используйте Neon.tech для PostgreSQL
#
# Преимущества Docker деплоймента:
# - Решает проблемы компиляции (psycopg2-binary, Rust)
# - Предустановленные системные зависимости
# - Изолированная среда
# - Воспроизводимые сборки
# - Лучшая отладка
