services:
  # Backend API
  - type: web
    name: lightnovel-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python init_db.py
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    healthCheckTimeout: 300
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lightnovel-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lightnovel-redis
          property: connectionString
      - key: GEMINI_API_KEYS
        sync: false
      - key: GEMINI_API_LIMIT_PER_KEY
        value: 1000
      - key: GEMINI_API_LIMIT_THRESHOLD_PERCENT
        value: 95
      - key: GEMINI_API_COOLDOWN_HOURS
        value: 24
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://lightnovel-frontend.onrender.com

  # Frontend
  - type: web
    name: lightnovel-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://lightnovel-backend.onrender.com

  # Celery Worker
  - type: worker
    name: lightnovel-worker
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      celery -A app.tasks.celery_app worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lightnovel-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lightnovel-redis
          property: connectionString
      - key: GEMINI_API_KEYS
        sync: false
      - key: GEMINI_API_LIMIT_PER_KEY
        value: 1000
      - key: GEMINI_API_LIMIT_THRESHOLD_PERCENT
        value: 95
      - key: GEMINI_API_COOLDOWN_HOURS
        value: 24
      - key: ENVIRONMENT
        value: production

databases:
  - name: lightnovel-db
    databaseName: lightnovel
    user: lightnovel_user
    plan: free

services:
  - type: redis
    name: lightnovel-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
