"""
Integration tests — pgvector semantic search.

Level: Integration (requires live PostgreSQL + pgvector extension).
Marker: @pytest.mark.postgres

These tests are ALWAYS SKIPPED locally unless --postgres-url is supplied:
    pytest -m postgres --postgres-url=postgresql://user:pass@localhost/testdb

In CI, the GitHub Actions / Northflank pipeline should:
  1. Spin up postgres:15-pgvector as a service container.
  2. Pass --postgres-url=$TEST_PG_URL to pytest.

Coverage:
  EmbeddingService:
    - generate_embedding() → 768-dim L2-normalized vector
    - vector_to_pgvector_literal() → valid pgvector literal
    - find_similar_terms() → HNSW approximate nearest neighbour search
    - find_similar_terms() threshold filtering
    - find_similar_terms() with no embeddings stored → empty result

  DB schema:
    - pgvector extension is available
    - glossary_terms.embedding_vec column stores/retrieves vector(768)

Notes:
  - Gemini API is MOCKED (no real calls). Embeddings are deterministic
    synthetic vectors generated by `_make_unit_vec()`.
  - Tests do NOT depend on a pre-existing database — postgres_db fixture
    creates all tables fresh and drops them on teardown.
"""

import math
import pytest
from sqlalchemy.orm import Session
from sqlalchemy import text


# ── Helpers ────────────────────────────────────────────────────────────────────


def _make_unit_vec(value: float, dim: int = 768) -> list[float]:
    """
    Create a unit vector where all components are equal, pointing in direction
    `value` (sign determines similarity cluster). After L2 normalization the
    result is a valid unit vector.
    """
    component = value / math.sqrt(dim)
    return [component] * dim


def _store_embedding(db: Session, term_id: int, vec: list[float]) -> None:
    """Insert a pgvector embedding directly via raw SQL (bypasses ORM type system)."""
    vec_literal = "[" + ",".join(f"{v:.8f}" for v in vec) + "]"
    db.execute(
        text("UPDATE glossary_terms SET embedding_vec = :vec::vector WHERE id = :tid"),
        {"vec": vec_literal, "tid": term_id},
    )
    db.commit()


# ── pgvector schema tests ──────────────────────────────────────────────────────


@pytest.mark.postgres
class TestPgvectorSchema:
    def test_pgvector_extension_is_available(self, postgres_db: Session):
        # Arrange + Act
        result = postgres_db.execute(
            text("SELECT extname FROM pg_extension WHERE extname = 'vector'")
        ).fetchone()

        # Assert
        assert result is not None, (
            "pgvector extension not found. Run: CREATE EXTENSION vector;"
        )

    def test_embedding_vec_column_exists_on_glossary_terms(self, postgres_db: Session):
        # Arrange + Act
        result = postgres_db.execute(
            text(
                "SELECT column_name, data_type FROM information_schema.columns "
                "WHERE table_name = 'glossary_terms' AND column_name = 'embedding_vec'"
            )
        ).fetchone()

        # Assert
        assert result is not None, (
            "embedding_vec column missing from glossary_terms. "
            "Run migration 015_add_pgvector_embeddings."
        )

    def test_embedding_vec_column_accepts_768_dim_vector(self, postgres_db: Session):
        # Arrange
        from tests.conftest import make_project, make_glossary_term

        project = make_project(postgres_db)
        term = make_glossary_term(postgres_db, project.id, source_term="Dragon")
        vec = _make_unit_vec(1.0)

        # Act — storing a 768-dim vector must not raise
        _store_embedding(postgres_db, term.id, vec)

        # Assert — retrieved via raw SQL round-trips correctly
        result = postgres_db.execute(
            text(
                "SELECT embedding_vec IS NOT NULL FROM glossary_terms WHERE id = :tid"
            ),
            {"tid": term.id},
        ).scalar()
        assert result is True


# ── EmbeddingService unit tests (pure, no DB) ─────────────────────────────────


@pytest.mark.postgres
class TestEmbeddingServiceUnitWithPg:
    """
    Unit tests for EmbeddingService pure methods that don't need a live DB.
    Marked postgres because they depend on numpy (which may be absent on CI
    without the full requirements).
    """

    def test_l2_normalize_produces_unit_vector(self, postgres_db: Session):
        # Arrange
        from app.services.embedding_service import EmbeddingService

        raw = [3.0, 4.0] + [0.0] * 766  # norm = 5.0

        # Act
        normalized = EmbeddingService._l2_normalize(raw)

        # Assert
        magnitude = math.sqrt(sum(v**2 for v in normalized))
        assert abs(magnitude - 1.0) < 1e-5

    def test_vector_to_pgvector_literal_produces_valid_format(
        self, postgres_db: Session
    ):
        # Arrange
        from app.services.embedding_service import EmbeddingService

        svc = EmbeddingService()
        vec = [0.1, 0.2, 0.3]

        # Act
        literal = svc.vector_to_pgvector_literal(vec)

        # Assert
        assert literal.startswith("[")
        assert literal.endswith("]")
        # Each component must be present (allow floating-point formatting)
        assert "0.10000000" in literal
        assert "0.20000000" in literal

    def test_generate_embedding_returns_none_for_empty_string(
        self, postgres_db: Session
    ):
        # Arrange
        from app.services.embedding_service import EmbeddingService

        svc = EmbeddingService()

        # Act
        result = svc.generate_embedding("")

        # Assert
        assert result is None

    def test_generate_embedding_returns_none_for_whitespace_only(
        self, postgres_db: Session
    ):
        # Arrange
        from app.services.embedding_service import EmbeddingService

        svc = EmbeddingService()

        # Act
        result = svc.generate_embedding("   ")

        # Assert
        assert result is None


# ── find_similar_terms ─────────────────────────────────────────────────────────


@pytest.mark.postgres
class TestFindSimilarTerms:
    def test_returns_exact_match_when_identical_embedding_stored(
        self, postgres_db: Session, mock_gemini
    ):
        # Arrange
        from app.services.embedding_service import EmbeddingService
        from tests.conftest import make_project, make_glossary_term

        project = make_project(postgres_db, name="Embed Project")
        term = make_glossary_term(postgres_db, project.id, source_term="Sword of Light")
        query_vec = _make_unit_vec(1.0)
        _store_embedding(postgres_db, term.id, query_vec)

        svc = EmbeddingService()

        # Act
        results = svc.find_similar_terms(
            postgres_db, query_vec, project_id=project.id, limit=5, threshold=0.99
        )

        # Assert
        assert len(results) == 1
        assert results[0]["source_term"] == "Sword of Light"
        assert results[0]["similarity"] >= 0.99

    def test_returns_empty_when_no_embeddings_stored(self, postgres_db: Session):
        # Arrange
        from app.services.embedding_service import EmbeddingService
        from tests.conftest import make_project, make_glossary_term

        project = make_project(postgres_db, name="Empty Embed Project")
        make_glossary_term(postgres_db, project.id, source_term="Shadow Realm")
        # No embedding stored ↑

        svc = EmbeddingService()
        query_vec = _make_unit_vec(1.0)

        # Act
        results = svc.find_similar_terms(
            postgres_db, query_vec, project_id=project.id, limit=5
        )

        # Assert
        assert results == []

    def test_threshold_filters_out_dissimilar_terms(self, postgres_db: Session):
        # Arrange
        from app.services.embedding_service import EmbeddingService
        from tests.conftest import make_project, make_glossary_term

        project = make_project(postgres_db, name="Threshold Project")
        similar_term = make_glossary_term(postgres_db, project.id, source_term="Hero")
        dissimilar_term = make_glossary_term(
            postgres_db, project.id, source_term="Villain"
        )

        # Hero → same cluster as query (cosine sim ≈ 1.0)
        _store_embedding(postgres_db, similar_term.id, _make_unit_vec(1.0))
        # Villain → opposite direction (cosine sim ≈ 0)
        _store_embedding(postgres_db, dissimilar_term.id, _make_unit_vec(-1.0))

        svc = EmbeddingService()
        query_vec = _make_unit_vec(1.0)

        # Act — high threshold should exclude Villain
        results = svc.find_similar_terms(
            postgres_db, query_vec, project_id=project.id, limit=10, threshold=0.9
        )

        # Assert
        terms_found = {r["source_term"] for r in results}
        assert "Hero" in terms_found
        assert "Villain" not in terms_found

    def test_respects_project_id_isolation(self, postgres_db: Session):
        # Arrange — two projects, each with a term + embedding
        from app.services.embedding_service import EmbeddingService
        from tests.conftest import make_project, make_glossary_term

        project_a = make_project(postgres_db, name="Project A")
        project_b = make_project(postgres_db, name="Project B")

        term_a = make_glossary_term(postgres_db, project_a.id, source_term="Knight")
        term_b = make_glossary_term(postgres_db, project_b.id, source_term="Rogue")

        vec = _make_unit_vec(1.0)
        _store_embedding(postgres_db, term_a.id, vec)
        _store_embedding(postgres_db, term_b.id, vec)

        svc = EmbeddingService()

        # Act — query only project_a
        results = svc.find_similar_terms(
            postgres_db, vec, project_id=project_a.id, limit=10, threshold=0.0
        )

        # Assert — only Knight (from project_a) is returned
        terms_found = {r["source_term"] for r in results}
        assert "Knight" in terms_found
        assert "Rogue" not in terms_found
